/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Setting = {
  _id: string
  _type: 'setting'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteUrl?: string
  legalName?: string
  comercialName?: string
  foundingDate?: string
  postalAddress?: string
  googleMapsUrl?: string
  phone?: string
  email?: string
  socialLinks?: Array<string>
}

export type Contact = {
  _id: string
  _type: 'contact'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
}

export type SharedSection = {
  _id: string
  _type: 'sharedSection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  language?: 'es' | 'en'
  pageSections?: Array<
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'sharedSection'
      }
    | ({
        _key: string
      } & HeroHome)
    | ({
        _key: string
      } & HeroBasic)
    | ({
        _key: string
      } & Banner)
    | ({
        _key: string
      } & SectionCarousel)
    | ({
        _key: string
      } & SectionCarouselPostFilter)
    | ({
        _key: string
      } & SectionPublicationsCarousel)
    | ({
        _key: string
      } & SectionGallery)
    | ({
        _key: string
      } & Stories)
    | ({
        _key: string
      } & SectionBasic)
  >
}

export type Legal = {
  _id: string
  _type: 'legal'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  contentList?: string
}

export type Post = {
  _id: string
  _type: 'Post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  description?: string
  contentCopy?: string
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Category'
  }
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Author'
  }
}

export type HomeBlog = {
  _id: string
  _type: 'homeBlog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  pageSections?: Array<
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'sharedSection'
      }
    | ({
        _key: string
      } & HeroHome)
    | ({
        _key: string
      } & HeroBasic)
    | ({
        _key: string
      } & Banner)
    | ({
        _key: string
      } & SectionCarousel)
    | ({
        _key: string
      } & SectionCarouselPostFilter)
    | ({
        _key: string
      } & SectionPublicationsCarousel)
    | ({
        _key: string
      } & SectionGallery)
    | ({
        _key: string
      } & Stories)
    | ({
        _key: string
      } & SectionBasic)
  >
}

export type Banner = {
  _type: 'banner'
  copy?: string
  cta?: Array<
    {
      _key: string
    } & Cta
  >
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  media?: {
    type?: 'photo' | 'video'
    photo?: Photo
    video?: Video
  }
}

export type Stories = {
  _type: 'stories'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type SectionCarouselPostFilter = {
  _type: 'sectionCarouselPostFilter'
  copy?: string
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Category'
  }
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Author'
  }
  limit?: number
}

export type Author = {
  _id: string
  _type: 'Author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  nameAuthor?: string
  bio?: string
  email?: string
  post?: string
  socialLinkList?: Array<string>
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Category = {
  _id: string
  _type: 'Category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  contentCopy?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SectionPublicationsCarousel = {
  _type: 'sectionPublicationsCarousel'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type SectionGallery = {
  _type: 'sectionGallery'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
  galleryStyles?: 'mosaic' | 'carousel' | 'grid'
}

export type Sections = Array<
  | {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'sharedSection'
    }
  | ({
      _key: string
    } & HeroHome)
  | ({
      _key: string
    } & HeroBasic)
  | ({
      _key: string
    } & Banner)
  | ({
      _key: string
    } & SectionCarousel)
  | ({
      _key: string
    } & SectionCarouselPostFilter)
  | ({
      _key: string
    } & SectionPublicationsCarousel)
  | ({
      _key: string
    } & SectionGallery)
  | ({
      _key: string
    } & Stories)
  | ({
      _key: string
    } & SectionBasic)
>

export type SectionCarousel = {
  _type: 'sectionCarousel'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type SectionBasic = {
  _type: 'sectionBasic'
  copy?: string
  cta?: Array<
    {
      _key: string
    } & Cta
  >
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  media?: {
    type?: 'photo' | 'video'
    photo?: Photo
    video?: Video
  }
  reverse?: boolean
}

export type Summary = {
  _type: 'summary'
  title?: string
  text?: string
  photo?: string
}

export type HeroHome = {
  _type: 'heroHome'
  copy?: string
  cta?: Array<
    {
      _key: string
    } & Cta
  >
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  media?: {
    type?: 'photo' | 'video'
    photo?: Photo
    video?: Video
  }
}

export type HeroBasic = {
  _type: 'heroBasic'
  copy?: string
  cta?: Array<
    {
      _key: string
    } & Cta
  >
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  media?: {
    type?: 'photo' | 'video'
    photo?: Photo
    video?: Video
  }
}

export type Theme = {
  _id: string
  _type: 'theme'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  backgroundColor?: string
  secondColor?: string
  textColor?: string
}

export type Metadata = {
  _type: 'metadata'
  title?: string
  description?: string
  canonical?: string
  robots?: 'index, follow' | 'index, nofollow' | 'noindex, follow' | 'noindex, nofollow'
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Cta = {
  _type: 'cta'
  type?: 'link' | 'popup'
  url?: string
  popupRef?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'popup'
  }
  buttonStyle?: 'primary' | 'secondary' | 'tertiary'
}

export type Popup = {
  _id: string
  _type: 'popup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  ref?: string
  copy?: string
  showPhone?: boolean
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  details?: string
  language?: 'es' | 'en'
}

export type Video = {
  _type: 'video'
  alt?: string
  srcLaptop?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  srcMobile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Photo = {
  _type: 'photo'
  alt?: string
  asset?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Markdown = string

export type Table = {
  _type: 'table'
  rows?: Array<
    {
      _key: string
    } & TableRow
  >
}

export type TableRow = {
  _type: 'tableRow'
  cells?: Array<string>
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Setting
  | Contact
  | SharedSection
  | Legal
  | Post
  | HomeBlog
  | Banner
  | Stories
  | SectionCarouselPostFilter
  | Author
  | Category
  | Slug
  | SectionPublicationsCarousel
  | SectionGallery
  | Sections
  | SectionCarousel
  | SectionBasic
  | Summary
  | HeroHome
  | HeroBasic
  | Theme
  | Metadata
  | Cta
  | Popup
  | Video
  | SanityFileAsset
  | Photo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Markdown
  | Table
  | TableRow
export declare const internalGroqTypeReferenceTo: unique symbol
