/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Post = {
  _id: string
  _type: 'Post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  hero?: HeroPost
  pageSections?: Array<
    {
      _key: string
    } & SectionMarkdown
  >
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Category'
  }
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Author'
  }
}

export type Author = {
  _id: string
  _type: 'Author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  author?: string
  bio?: string
  job?: string
  keywords?: Array<string>
  cv?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  image?: Photo
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
}

export type HomeBlog = {
  _id: string
  _type: 'homeBlog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  hero?: HeroHome
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  pageSections?: Array<
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'Post'
      }
    | ({
        _key: string
      } & SectionCarouselPostFilter)
  >
}

export type PostSections = Array<
  {
    _key: string
  } & SectionMarkdown
>

export type Sections = Array<
  | {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'Post'
    }
  | ({
      _key: string
    } & SectionCarouselPostFilter)
>

export type SectionCarouselPostFilter = {
  _type: 'sectionCarouselPostFilter'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'Category'
  }
}

export type Category = {
  _id: string
  _type: 'Category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  language?: 'es' | 'en'
  metas?: Metadata
  summary?: Summary
  ref?: string
  heroBasic?: HeroBasic
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Banner = {
  _type: 'banner'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type SectionMarkdown = {
  _type: 'sectionMarkdown'
  content?: string
}

export type SectionBasic = {
  _type: 'sectionBasic'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
  reverse?: boolean
}

export type HeroPost = {
  _type: 'heroPost'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type HeroBasic = {
  _type: 'heroBasic'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type HeroHome = {
  _type: 'heroHome'
  copy?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type AttachedInSanity = {
  _type: 'attachedInSanity'
  asset?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    caption?: string
    _type: 'file'
  }
}

export type Video = {
  _type: 'video'
  alt?: string
  srcLaptop?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  srcMobile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type Photo = {
  _type: 'photo'
  photo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    _type: 'image'
  }
}

export type Metadata = {
  _type: 'metadata'
  title?: string
  description?: string
  canonical?: string
  robots?: 'index, follow' | 'index, nofollow' | 'noindex, follow' | 'noindex, nofollow'
  photo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    _type: 'image'
  }
}

export type Summary = {
  _type: 'summary'
  title?: string
  text?: string
  theme?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'theme'
  }
  mediaList?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & Video)
  >
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Theme = {
  _id: string
  _type: 'theme'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  backgroundColor?: string
  textColor?: string
}

export type Markdown = string

export type Table = {
  _type: 'table'
  rows?: Array<
    {
      _key: string
    } & TableRow
  >
}

export type TableRow = {
  _type: 'tableRow'
  cells?: Array<string>
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Post
  | Author
  | HomeBlog
  | PostSections
  | Sections
  | SectionCarouselPostFilter
  | Category
  | Slug
  | Banner
  | SectionMarkdown
  | SectionBasic
  | HeroPost
  | HeroBasic
  | HeroHome
  | AttachedInSanity
  | Video
  | Photo
  | Metadata
  | Summary
  | SanityFileAsset
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Theme
  | Markdown
  | Table
  | TableRow
export declare const internalGroqTypeReferenceTo: unique symbol
