export type ApiResponse = {
    success: boolean;
    code: number;
    psdata: FeaturedProduct[];
};

export type FeaturedProduct = {
    images: ProductImage[];
    id_product: string;
    id_supplier: string;
    id_manufacturer: string;
    id_category_default: string;
    id_shop_default: string;
    id_tax_rules_group: string;
    on_sale: string;
    online_only: string;
    ean13: string;
    isbn: string;
    upc: string;
    mpn: string;
    ecotax: string;
    quantity: number;
    minimal_quantity: string;
    low_stock_threshold: string;
    low_stock_alert: string;
    price: string;
    wholesale_price: string;
    unity: string;
    unit_price: string;
    unit_price_ratio: number;
    additional_shipping_cost: string;
    reference: string;
    supplier_reference: string;
    location: string;
    width: string;
    height: string;
    depth: string;
    weight: string;
    out_of_stock: string;
    additional_delivery_times: string;
    quantity_discount: string;
    customizable: string;
    uploadable_files: string;
    text_fields: string;
    active: string;
    redirect_type: string;
    id_type_redirected: string;
    available_for_order: string;
    available_date: string | null;
    show_condition: string;
    condition: string;
    show_price: string;
    indexed: string;
    visibility: string;
    cache_is_pack: string;
    cache_has_attachments: string;
    is_virtual: string;
    cache_default_attribute: string;
    date_add: string;
    date_upd: string;
    advanced_stock_management: string;
    pack_stock_type: string;
    state: string;
    product_type: string;
    id_shop: string;
    id_lang: string;
    description: string;
    description_short: string;
    link_rewrite: string;
    meta_description: string;
    meta_keywords: string;
    meta_title: string;
    name: string;
    available_now: string;
    available_later: string;
    delivery_in_stock: string;
    delivery_out_stock: string;
    new: string;
    id_product_attribute: number;
    product_attribute_minimal_quantity: string;
    id_image: string;
    legend: string;
    manufacturer_name: string | null;
    category_default: string;
    orderprice: string;
    allow_oosp: number;
    cover_image_id: string;
    category: string;
    category_name: string;
    link: string;
    attribute_price: number;
    price_tax_exc: number;
    price_without_reduction_without_tax: number;
    price_without_reduction: number;
    reduction: number;
    reduction_without_tax: number;
    specific_prices: any[];
    quantity_all_versions: number;
    features: any[];
    attachments: any[];
    virtual: number;
    pack: number;
    packItems: any[];
    nopackprice: number;
    customization_required: boolean;
    attributes: Record<string, ProductAttribute>;
    rate: number;
    tax_name: string;
    ecotax_rate: number;
    unit_price_tax_excluded: number;
    unit_price_tax_included: number;
    default_image: ImageObject;
    cover: ImageObject;
    has_discount: boolean;
    discount_type: string | null;
    discount_percentage: string | null;
    discount_percentage_absolute: number | null;
    discount_amount: number | null;
    discount_amount_to_display: string | null;
    price_amount: number;
    regular_price_amount: number;
    regular_price: string;
    discount_to_display: string | null;
    unit_price_full: string;
    show_availability: boolean;
    availability_date: string | null;
    availability_message: string;
    availability: string;
};

export type ProductAttribute = {
    id_attribute: string;
    id_attribute_group: string;
    name: string;
    group: string;
    public_group: string;
    reference: string;
    ean13: string;
    isbn: string;
    upc: string;
    mpn: string;
    available_now: string;
    available_later: string;
};

export type ImageObject = {
    url: string;
    width: number;
    height: number;
    sources: {
        jpg: string;
    };
};

export type ImageSize = {
    url: string;
    width: number;
    height: number;
    sources: {
        jpg: string;
    };
};

export type ProductImage = {
    cover: string | null;
    id_image: string;
    legend: string;
    position: string;
    bySize: {
        small_default: ImageSize;
        cart_default: ImageSize;
        home_default: ImageSize;
        medium_default: ImageSize;
        large_default: ImageSize;
    };
    small: ImageSize;
    medium: ImageSize;
    large: ImageSize;
    associatedVariants: string[];
};
