import fs from "fs";

const PATH_TO_ITCSS = "./src/styles/";

export async function autoIndexITCSS() {
    const directories = [
        "generic",
        "elements",
        "objects",
        "layouts",
        "components/atoms",
        "utilities",
    ];

    for (const dir of directories) {
        await createIndexScssAndAddInITCSS(`${PATH_TO_ITCSS}${dir}`);
    }
}

async function createIndexScssAndAddInITCSS(directoryPath) {
    try {
        const filesInDirectory = await fs.promises.readdir(directoryPath);
        const pathArray = directoryPath.split("/");
        const nameLastFolder = pathArray[pathArray.length - 1];
        const filesInDirectoryToExport = [];

        for (const file of filesInDirectory) {
            if (file.includes(nameLastFolder)) {
                continue;
            }
            const fileWithout_ = file.replace("_", "");
            filesInDirectoryToExport.push(`@use "${fileWithout_}";`);
        }

        filesInDirectoryToExport.unshift(
            `// File autogenerated by gatsby-node.ts in function autoIndexITCSS`,
        );

        const linesToWrite = filesInDirectoryToExport.join("\n");
        await fs.promises.writeFile(
            `${directoryPath}/_${nameLastFolder}.scss`,
            linesToWrite,
        );
    } catch (error) {
        console.error(`Error processing directory ${directoryPath}: `, error);
    }
}
